### ISSUE TITLE
NPE in BTreeMap (version 1.0.4)

### ISSUE THREAD

**Issue by samhendley** [jankotek/MapDB#411] opened 2014-11-24 21:21 UTC
I found one of my servers in a very unhappy state and I am trying to figure out how this occurred and if this has been fixed in a more recent version. 

Here is my map definition, the endpoint serializer is a trivial serializer that outputs reads and writes 2 integers.
```java
db.createTreeMap("endpointInfo")
                .counterEnable()
                .keySerializer(BTreeKeySerializer.ZERO_OR_POSITIVE_INT)
                .valueSerializer(new EndpointInformationSerializer())
                .<Integer, EndpointInformation> makeOrGet()
```

Everyone of my queries to my map were failing with the following error NPE.

```
java.lang.NullPointerException
        at org.mapdb.BTreeMap.get(BTreeMap.java:600)
        at org.mapdb.BTreeMap.get(BTreeMap.java:589)
```

Here is the code from MapDb 1.0.4:

```java
    @Override
     public V get(Object key){
    	return (V) get(key, true);
    }

    protected Object get(Object key, boolean expandValue) {
        if(key==null) throw new NullPointerException();
        K v = (K) key;
        long current = engine.get(rootRecidRef, Serializer.LONG); //get root

        BNode A = engine.get(current, nodeSerializer);

        //dive until  leaf
        while(!A.isLeaf()){
            current = nextDir((DirNode) A, v);
            A = engine.get(current, nodeSerializer);
        }
```

When I restarted the application to enable debugging I got this exception which prevented me from loading the database: 

```
Caused by: java.lang.AssertionError: data were read beyond record size, check your serializer
        at org.mapdb.Store.deserialize(Store.java:301)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
        at org.mapdb.StoreDirect.get(StoreDirect.java:428)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:401)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.Caches$LRU.get(Caches.java:84)
        at org.mapdb.Caches$HardRef.get(Caches.java:613)
        at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
        at org.mapdb.DB.getTreeMap(DB.java:788)
        at org.mapdb.DB$BTreeMapMaker.makeOrGet(DB.java:650)
```       

There wasn't anything particular in the changelog that seemed related to this problem but the BTreeMap code has changed. Any chance this bug has been found and fixed before? I am planning to update to 1.0.6 in any case but any advice you can give me about this bug would be appreciated.

**Comment by jankotek** [comment] 2015-02-17 09:45
Outdated version, could not reproduce, closing

**Closed by jankotek** 2015-02-17 09:45 UTC
Labels: 1.0, bug
