### ISSUE TITLE
Allow fileDB to take InputStream in addition to File or String

### ISSUE THREAD

**Issue by knoodrake** [jankotek/mapdb#820] opened 2017-04-09 15:28 UTC
That would allow, for instance, to open jar-embeded db files

**Comment by scottcarey** [comment] 2017-04-10 18:21
The problem is, that you can not seek an InputStream at random.  However, it could be read into RAM fully, but in that case it is not a fileDB.

**Comment by knoodrake** [comment] 2017-04-11 02:04
Indeed. Didn't thought about that, my bad. Anyway, It can be handy to have a pre-built db file that you can either read from a file or from a jar. Also, If one could "seek", trough the pre-built db in RAM, only the "compressed" (serialized would be the correct term I suppose) db would take space in memory, as opposed to loading the entire source of raw data to RAM to build the DB on the fly. But I'm not very well aware of the insights of mapdb, so I guess I may be entirely wrong..

**Comment by jankotek** [comment] 2017-04-11 08:13
This should be addressed as part of Data Pump changes. DB takes an compressed InputStream, and saves it into temporary file or in-memory buffer. 
It is part of other issues, so closing this one.

**Closed by jankotek** 2017-04-11 08:13 UTC
