### ISSUE TITLE
inconsistent index

### ISSUE THREAD

**Issue by ovear** [jankotek/mapdb#713] opened 2016-05-20 02:22 UTC
Hello, i got this error after i insert information to mapdb.
My mapdb version is mapdb-3.0-beta4 (M6 are the same problem)

this is the stack trace

> Error: inconsistent index
> org.mapdb.DBException$DataCorruption: inconsistent index
>         at org.mapdb.IndexTreeListJava.treePutSub(IndexTreeListJava.java:363)
>         at org.mapdb.IndexTreeListJava.treePut(IndexTreeListJava.java:344)
>         at org.mapdb.IndexTreeLongLongMap.put(IndexTreeLongLongMap.kt:72)
>         at org.mapdb.HTreeMap.putInternal$mapdb(HTreeMap.kt:363)
>         at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
>         and something others
>         at java.lang.Thread.run(Thread.java:745)
> Error: inconsistent index
> org.mapdb.DBException$DataCorruption: inconsistent index
>         at org.mapdb.IndexTreeListJava.treePutSub(IndexTreeListJava.java:363)
>         at org.mapdb.IndexTreeListJava.treePut(IndexTreeListJava.java:344)
>         at org.mapdb.IndexTreeLongLongMap.put(IndexTreeLongLongMap.kt:72)
>         at org.mapdb.HTreeMap.putInternal$mapdb(HTreeMap.kt:363)
>         at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
>         and something others
>         at info.ovear.Main.lambda$syncMusic$0(Main.java:158)
>         at java.lang.Thread.run(Thread.java:745)
> Error: inconsistent index
> org.mapdb.DBException$DataCorruption: inconsistent index
>         at org.mapdb.IndexTreeListJava.treePutSub(IndexTreeListJava.java:363)
>         at org.mapdb.IndexTreeListJava.treePut(IndexTreeListJava.java:344)
>         at org.mapdb.IndexTreeLongLongMap.put(IndexTreeLongLongMap.kt:72)
>         at org.mapdb.HTreeMap.putInternal$mapdb(HTreeMap.kt:363)
>         at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
>         and something others
>         at java.lang.Thread.run(Thread.java:745)
> Error: inconsistent index

i use follow code to init mapdb

```
    private DB db;
    private HTreeMap<String, List<DataPoint>> dataPointDb;

        db = DBMaker.fileDB("mydb.db2")
                        fileMmapEnableIfSupported().
                        transactionEnable().
                        closeOnJvmShutdown().
                        make();
        dataPointDb = db.hashMap("mymap").
                keySerializer(Serializer.STRING).
                valueSerializer(new SerializerCompressionWrapper(Serializer.ELSA)).
                counterEnable().
                layout(16, 64, 4).
                createOrOpen();
```

and just use dataPointDb.put to insert data to mapdb, and finally use db.close() to close db.

Then, if i open this db again, it will throw the “inconsistent index” exception.

**Comment by ovear** [comment] 2016-05-20 06:09
oh, i found the problem.
it seems that mapdb.get() method always create new object?

```
        DB db = DBMaker.fileDB("test.db2").
            fileMmapEnableIfSupported().
            transactionEnable().
            closeOnJvmShutdown().
            make();
        //Maximal Hash Table Size is calculated as: segment * node size ^ level count.
        HTreeMap<String, List<String>> map = db.hashMap("hahaha").
                keySerializer(Serializer.STRING).
                valueSerializer(new SerializerCompressionWrapper(Serializer.ELSA)).
                counterEnable().
                layout(16, 64, 4).
                createOrOpen();


        List<String> list = Collections.synchronizedList(new LinkedList<>());
        list.add("testa");
        list.add("testb");
//        map.put("abc", list);
        List<String> list1 = map.get("abc");
        List<String> list2 = map.get("abc");
        System.out.println(list1.hashCode());
        System.out.println(list2.hashCode());
        System.out.println(list1.hashCode() == list2.hashCode());
        System.out.println(list1 == list2);
        System.out.println(list1);
        System.out.println(list2);
        list1.add("testc");
        System.out.println(list1);
        System.out.println(list2);
        System.out.println(map.get("abc"));
```

This is my test code, and output is a little bit of strange

```
-766917214
-766917214
true
false
[testa, testb]
[testa, testb]
[testa, testb, testc]
[testa, testb]
[testa, testb]
```

it shows that list1 and list have the same hashcode, but they are not the same object.
and map.get() always create new object, and won't keep an unique object in the memory like HashMap in the Java.

is there any way to prevent mapdb.get() create object every time and sync with the unique object in the memory?

**Comment by ovear** [comment] 2016-05-20 07:20
em.. it seems that it is still a strange bug.
once i use transactionEnable() to enable transaction, it will occur some unexpected problem.

i use following code to test this

```
        DB db = DBMaker.fileDB("test.db2").
            transactionEnable().
            make();
        HTreeMap<String, List<String>> map = db.hashMap("hahaha").
                keySerializer(Serializer.STRING).
                valueSerializer(new SerializerCompressionWrapper(Serializer.ELSA)).
                counterEnable().
                layout(16, 64, 4).
                createOrOpen();

        //insert test data
        for(int i = 0; i < 100; i++){
            List<String> tmp = Collections.synchronizedList(new LinkedList<>());
            tmp.add(String.valueOf(i));
            map.put(String.valueOf(i), tmp);
        }

        //use key to get obj
//        for(int i = 0; i < 100; i++){
//            System.out.println(map.get(String.valueOf(i)));
//        }

        //use entrySet to get obj
//        for(Object o : map.entrySet()){
//            Map.Entry<String, List<String>> entry = (Map.Entry<String, List<String>>) o;
//            System.out.printf("%s => %s\n", entry.getKey(), entry.getValue());
//        }

        db.commit();
        db.close();
```

insert is works fine, not doesn't throw any exception or error, but if i try to get them from db, it will make some strange result.

like use key to get value

```
[0]
[1]
[2]
[3]
[4]
null
[6]
[7]
[8]
[9]
[10]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at org.mapdb.DataInput2$ByteArray.unpackInt(DataInput2.java:162)
	at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:225)
	at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:214)
	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:225)
	at org.mapdb.StoreWAL.get(StoreWAL.kt:505)
	at org.mapdb.HTreeMap.leafGet(HTreeMap.kt:1372)
	at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:633)
	at org.mapdb.HTreeMap.get(HTreeMap.kt:603)
	at info.ovear.Main.main(Main.java:58)
```

some key will just return null, but i am sure that i have inserted object before, and some object seems broken, once i use "get" to get them, it will throw exception. 
and if i disable transaction, everything will be ok.

**Comment by shabanovd** [comment] 2016-05-20 08:36
I can confirm that `transactionEnable()` lead to strange exceptions.

**Comment by jankotek** [comment] 2016-05-24 16:42
I believe this was caused by data corruption bug. It manifested only with transactions enabled. It was fixed yesterday and beta5 includes fix.

**Comment by jankotek** [comment] 2016-05-29 15:25
Closing, fixed in beta5

**Closed by jankotek** 2016-05-29 15:25 UTC
Labels: 3.0, bug
