### ISSUE TITLE
HTreeMap behaves different from java.util.HashMap

### ISSUE THREAD

**Issue by pweinroth** [jankotek/MapDB#434] opened 2015-01-22 20:17 UTC
Running with Trove 3.0.3 and MapDb 1.0.6 when we insert records into the treemap and then recover them using the cache key the string values on the HTreeMap have been changed to a null.  Using a hashmap this is not occurring.  

Could this be related to the handling of single quote, backslash, or utf-8 characters?

**Comment by jankotek** [comment] 2015-01-23 06:46
It looks like a bug. Would you have a code example?

Also a few common problems to diagnose/workaround:

 - are you values immutable?

 - is key hashing consistent? 

 - try to disable cache (`DBMaker.cacheDisable()`) and do not enable async writer. 

 - possibly transaction problem? commit have to be called to persist updates, or disable transactions.

**Comment by pweinroth** [comment] 2015-01-23 17:53
Let me pull out a simplified dataset and code example that reproduces the issue.  

The key hashing is consistent and the transaction is disabled. 

I will also give it a try with the cacheDisabled and make the objects immutable.

**Comment by jankotek** [comment] 2015-03-06 09:38
Closing. Not enough information to reproduce

**Closed by jankotek** 2015-03-06 09:38 UTC
Labels: 1.0, bug
